// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connection.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections
WHERE id = ?
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, name, driver, host, port, username, password, updated_at, created_at
FROM connections
WHERE id = ?
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, driver, host, port, username, password, updated_at, created_at
FROM connections
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Driver,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :exec
INSERT INTO connections (
    id,
    name,
    driver,
    host,
    port,
    username,
    password,
    updated_at,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE
SET name = excluded.name,
    driver = excluded.driver,
    host = excluded.host,
    port = excluded.port,
    username = excluded.username,
    password = excluded.password,
    updated_at = excluded.updated_at,
    created_at = excluded.created_at
`

type UpsertConnectionParams struct {
	ID        uuid.UUID
	Name      string
	Driver    string
	Host      string
	Port      int64
	Username  string
	Password  string
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}

func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnection,
		arg.ID,
		arg.Name,
		arg.Driver,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}
