// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Connection struct {
	ID        uuid.UUID
	Name      string
	Driver    string
	Host      string
	Port      int64
	Username  string
	Password  string
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}
