apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.fullname" . }}
  labels: {{ include "mesa.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "config.appKey is required" .Values.config.appKey | quote }}
