/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Mesa API
 * OpenAPI spec version: 0.1.0
 */
export type ConnectionDriver = typeof ConnectionDriver[keyof typeof ConnectionDriver];


export const ConnectionDriver = {
  postgres: 'postgres',
  mysql: 'mysql',
} as const;

export type ConnectionStatus = typeof ConnectionStatus[keyof typeof ConnectionStatus];


export const ConnectionStatus = {
  ok: 'ok',
  error: 'error',
} as const;

export interface Connection {
  id: string;
  /**
   * @minLength 3
   * @maxLength 255
   */
  name: string;
  driver: ConnectionDriver;
  /**
   * @minLength 1
   * @maxLength 255
   */
  host: string;
  /**
   * A port value between 0 and 65535
   * @minimum 0
   * @maximum 65535
   */
  port: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  username: string;
  createdAt?: string;
  updatedAt?: string;
  status?: ConnectionStatus;
  status_error?: string;
}

export interface Database {
  name: string;
  owner: string;
  encoding: string;
  size_formatted: string;
}

export interface Table {
  name: string;
  type: string;
  row_count: number;
  size: number;
}

export interface Column {
  name: string;
  type: string;
  primary: boolean;
  nullable: boolean;
  default_value?: string;
}

export interface TableRowsResponse {
  columns: string[];
  rows: unknown[][];
  total: number;
  limit: number;
  offset: number;
}

export interface Error {
  message: string;
}

export type CreateConnectionRequestDriver = typeof CreateConnectionRequestDriver[keyof typeof CreateConnectionRequestDriver];


export const CreateConnectionRequestDriver = {
  postgres: 'postgres',
  mysql: 'mysql',
} as const;

export interface CreateConnectionRequest {
  name: string;
  driver: CreateConnectionRequestDriver;
  host: string;
  port: number;
  username: string;
  password: string;
}

export type OverviewResponseStatus = typeof OverviewResponseStatus[keyof typeof OverviewResponseStatus];


export const OverviewResponseStatus = {
  ONLINE: 'ONLINE',
  UNREACHABLE: 'UNREACHABLE',
} as const;

export interface OverviewResponse {
  status: OverviewResponseStatus;
  version?: string;
  uptime?: string;
  sessions?: string;
  latency_ms: number;
}

export interface Session {
  pid: number;
  user: string;
  database: string;
  state: string;
  query: string;
  duration: string;
  is_slow: boolean;
}

export interface DBUser {
  name: string;
  is_superuser: boolean;
  can_login: boolean;
  conn_limit: number;
}

export interface CreateUserRequest {
  username: string;
  password: string;
  is_superuser?: boolean;
  can_login?: boolean;
  conn_limit?: number;
}

export interface CreateDatabaseRequest {
  name: string;
  owner: string;
}

export type ColumnDataType = typeof ColumnDataType[keyof typeof ColumnDataType];


export const ColumnDataType = {
  smallint: 'smallint',
  integer: 'integer',
  bigint: 'bigint',
  serial: 'serial',
  bigserial: 'bigserial',
  numeric: 'numeric',
  decimal: 'decimal',
  real: 'real',
  double_precision: 'double_precision',
  boolean: 'boolean',
  text: 'text',
  varchar: 'varchar',
  char: 'char',
  uuid: 'uuid',
  date: 'date',
  time: 'time',
  timestamp: 'timestamp',
  timestamptz: 'timestamptz',
  json: 'json',
  jsonb: 'jsonb',
  bytea: 'bytea',
} as const;

export interface CreateTableColumn {
  name: string;
  type: ColumnDataType;
  /** @minimum 1 */
  length?: number;
  /** @minimum 1 */
  precision?: number;
  nullable?: boolean;
  primary_key?: boolean;
  default_value?: string;
}

export type CreateTableIndexMethod = typeof CreateTableIndexMethod[keyof typeof CreateTableIndexMethod];


export const CreateTableIndexMethod = {
  btree: 'btree',
  hash: 'hash',
  gin: 'gin',
  gist: 'gist',
  brin: 'brin',
  spgist: 'spgist',
} as const;

export interface CreateTableIndex {
  name: string;
  /** @minItems 1 */
  columns: string[];
  unique?: boolean;
  method?: CreateTableIndexMethod;
}

export interface CreateTableRequest {
  name: string;
  /** @minItems 1 */
  columns: CreateTableColumn[];
  indexes?: CreateTableIndex[];
}

export type QueryTableRowsParams = {
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
sort_by?: string;
sort_order?: QueryTableRowsSortOrder;
};

export type QueryTableRowsSortOrder = typeof QueryTableRowsSortOrder[keyof typeof QueryTableRowsSortOrder];


export const QueryTableRowsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

