/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Mesa API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary List Connections
 */
export const listConnectionsResponseNameMin = 3;
export const listConnectionsResponseNameMax = 255;

export const listConnectionsResponseHostMax = 255;

export const listConnectionsResponsePortMin = 0;
export const listConnectionsResponsePortMax = 65535;

export const listConnectionsResponseUsernameMax = 255;



export const ListConnectionsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string().min(listConnectionsResponseNameMin).max(listConnectionsResponseNameMax),
  "driver": zod.enum(['postgres', 'mysql']),
  "host": zod.string().min(1).max(listConnectionsResponseHostMax),
  "port": zod.number().min(listConnectionsResponsePortMin).max(listConnectionsResponsePortMax).describe('A port value between 0 and 65535'),
  "username": zod.string().min(1).max(listConnectionsResponseUsernameMax),
  "createdAt": zod.iso.datetime({}).optional(),
  "updatedAt": zod.iso.datetime({}).optional(),
  "status": zod.enum(['ok', 'error']).optional(),
  "status_error": zod.string().optional()
})
export const ListConnectionsResponse = zod.array(ListConnectionsResponseItem)


/**
 * @summary Create Connection
 */
export const CreateConnectionBody = zod.object({
  "name": zod.string(),
  "driver": zod.enum(['postgres', 'mysql']),
  "host": zod.string(),
  "port": zod.number(),
  "username": zod.string(),
  "password": zod.string()
})


/**
 * @summary Retrieves a connection by ID
 */
export const FindConnectionParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const findConnectionResponseNameMin = 3;
export const findConnectionResponseNameMax = 255;

export const findConnectionResponseHostMax = 255;

export const findConnectionResponsePortMin = 0;
export const findConnectionResponsePortMax = 65535;

export const findConnectionResponseUsernameMax = 255;



export const FindConnectionResponse = zod.object({
  "id": zod.string(),
  "name": zod.string().min(findConnectionResponseNameMin).max(findConnectionResponseNameMax),
  "driver": zod.enum(['postgres', 'mysql']),
  "host": zod.string().min(1).max(findConnectionResponseHostMax),
  "port": zod.number().min(findConnectionResponsePortMin).max(findConnectionResponsePortMax).describe('A port value between 0 and 65535'),
  "username": zod.string().min(1).max(findConnectionResponseUsernameMax),
  "createdAt": zod.iso.datetime({}).optional(),
  "updatedAt": zod.iso.datetime({}).optional(),
  "status": zod.enum(['ok', 'error']).optional(),
  "status_error": zod.string().optional()
})


/**
 * @summary Checks the connection status
 */
export const PingConnectionParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})


/**
 * @summary List databases from a connection
 */
export const ListDatabasesParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const ListDatabasesResponseItem = zod.object({
  "name": zod.string(),
  "owner": zod.string(),
  "encoding": zod.string(),
  "size_formatted": zod.string()
})
export const ListDatabasesResponse = zod.array(ListDatabasesResponseItem)


/**
 * @summary Create a new database
 */
export const CreateDatabaseParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const CreateDatabaseBody = zod.object({
  "name": zod.string(),
  "owner": zod.string()
})


/**
 * @summary Get Server Health & Overview
 */
export const GetConnectionOverviewParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const GetConnectionOverviewResponse = zod.object({
  "status": zod.enum(['ONLINE', 'UNREACHABLE']),
  "version": zod.string().optional(),
  "uptime": zod.string().optional(),
  "sessions": zod.string().optional(),
  "latency_ms": zod.number()
})


/**
 * @summary List tables from a database
 */
export const ListTablesParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection'),
  "databaseName": zod.string().describe('Database name')
})

export const ListTablesResponseItem = zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "row_count": zod.number(),
  "size": zod.number()
})
export const ListTablesResponse = zod.array(ListTablesResponseItem)


/**
 * @summary Create a table in a database
 */
export const CreateTableParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection'),
  "databaseName": zod.string().describe('Database name')
})







export const CreateTableBody = zod.object({
  "name": zod.string(),
  "columns": zod.array(zod.object({
  "name": zod.string(),
  "type": zod.enum(['smallint', 'integer', 'bigint', 'serial', 'bigserial', 'numeric', 'decimal', 'real', 'double_precision', 'boolean', 'text', 'varchar', 'char', 'uuid', 'date', 'time', 'timestamp', 'timestamptz', 'json', 'jsonb', 'bytea']),
  "length": zod.number().min(1).optional(),
  "precision": zod.number().min(1).optional(),
  "nullable": zod.boolean().optional(),
  "primary_key": zod.boolean().optional(),
  "default_value": zod.string().optional()
})).min(1),
  "indexes": zod.array(zod.object({
  "name": zod.string(),
  "columns": zod.array(zod.string()).min(1),
  "unique": zod.boolean().optional(),
  "method": zod.enum(['btree', 'hash', 'gin', 'gist', 'brin', 'spgist']).optional()
})).optional()
})


/**
 * @summary ListColumns
 */
export const ListColumnsParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection'),
  "databaseName": zod.string().describe('Database name'),
  "tableName": zod.string().describe('Table Name')
})

export const ListColumnsResponseItem = zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "primary": zod.boolean(),
  "nullable": zod.boolean(),
  "default_value": zod.string().optional()
})
export const ListColumnsResponse = zod.array(ListColumnsResponseItem)


/**
 * @summary QueryTableRows
 */
export const QueryTableRowsParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection'),
  "databaseName": zod.string().describe('Database name'),
  "tableName": zod.string().describe('Table Name')
})

export const queryTableRowsQueryLimitDefault = 50;
export const queryTableRowsQueryLimitMax = 500;

export const queryTableRowsQueryOffsetDefault = 0;
export const queryTableRowsQueryOffsetMin = 0;

export const queryTableRowsQuerySortOrderDefault = `asc`;

export const QueryTableRowsQueryParams = zod.object({
  "limit": zod.number().min(1).max(queryTableRowsQueryLimitMax).default(queryTableRowsQueryLimitDefault),
  "offset": zod.number().min(queryTableRowsQueryOffsetMin).default(queryTableRowsQueryOffsetDefault),
  "sort_by": zod.string().optional(),
  "sort_order": zod.enum(['asc', 'desc']).default(queryTableRowsQuerySortOrderDefault)
})

export const QueryTableRowsResponse = zod.object({
  "columns": zod.array(zod.string()),
  "rows": zod.array(zod.array(zod.unknown())),
  "total": zod.number(),
  "limit": zod.number(),
  "offset": zod.number()
})


/**
 * @summary List database users (roles)
 */
export const ListUsersParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const ListUsersResponseItem = zod.object({
  "name": zod.string(),
  "is_superuser": zod.boolean(),
  "can_login": zod.boolean(),
  "conn_limit": zod.number()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary Create a new database user
 */
export const CreateUserParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const CreateUserBody = zod.object({
  "username": zod.string(),
  "password": zod.string(),
  "is_superuser": zod.boolean().optional(),
  "can_login": zod.boolean().optional(),
  "conn_limit": zod.number().optional()
})


/**
 * @summary List active sessions
 */
export const ListSessionsParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection')
})

export const ListSessionsResponseItem = zod.object({
  "pid": zod.number(),
  "user": zod.string(),
  "database": zod.string(),
  "state": zod.string(),
  "query": zod.string(),
  "duration": zod.string(),
  "is_slow": zod.boolean()
})
export const ListSessionsResponse = zod.array(ListSessionsResponseItem)


/**
 * @summary Kill a specific session
 */
export const KillSessionParams = zod.object({
  "connectionID": zod.uuid().describe('The unique identifier for the connection'),
  "pid": zod.number()
})
