// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connection.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections
WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, name, driver, host, port, username, password, updated_at, created_at
FROM connections
WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id pgtype.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, driver, host, port, username, password, updated_at, created_at
FROM connections
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Driver,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnection = `-- name: UpsertConnection :exec
INSERT INTO connections (
    id,
    name,
    driver,
    host,
    port,
    username,
    password,
    updated_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    driver = EXCLUDED.driver,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    username = EXCLUDED.username,
    password = EXCLUDED.password
`

type UpsertConnectionParams struct {
	ID        pgtype.UUID
	Name      string
	Driver    string
	Host      string
	Port      int32
	Username  string
	Password  string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertConnection,
		arg.ID,
		arg.Name,
		arg.Driver,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}
