// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connection struct {
	ID        pgtype.UUID
	Name      string
	Driver    string
	Host      string
	Port      int32
	Username  string
	Password  string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
