/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Mesa API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Column,
  Connection,
  CreateConnectionRequest,
  CreateDatabaseRequest,
  CreateTableRequest,
  CreateUserRequest,
  DBUser,
  Database,
  Error,
  OverviewResponse,
  Session,
  Table
} from '../mesaAPI.schemas';

import { customInstance } from '../../lib/fetch-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Connections
 */
export const getListConnectionsUrl = () => {


  

  return `/connections`
}

export const listConnections = async ( options?: RequestInit): Promise<Connection[]> => {
  
  return customInstance<Connection[]>(getListConnectionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListConnectionsQueryKey = () => {
    return [
    `/connections`
    ] as const;
    }

    
export const getListConnectionsQueryOptions = <TData = Awaited<ReturnType<typeof listConnections>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListConnectionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listConnections>>> = ({ signal }) => listConnections({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListConnectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listConnections>>>
export type ListConnectionsQueryError = unknown


export function useListConnections<TData = Awaited<ReturnType<typeof listConnections>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConnections>>,
          TError,
          Awaited<ReturnType<typeof listConnections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConnections<TData = Awaited<ReturnType<typeof listConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listConnections>>,
          TError,
          Awaited<ReturnType<typeof listConnections>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListConnections<TData = Awaited<ReturnType<typeof listConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Connections
 */

export function useListConnections<TData = Awaited<ReturnType<typeof listConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listConnections>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListConnectionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Connection
 */
export const getCreateConnectionUrl = () => {


  

  return `/connections`
}

export const createConnection = async (createConnectionRequest: CreateConnectionRequest, options?: RequestInit): Promise<Connection> => {
  
  return customInstance<Connection>(getCreateConnectionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createConnectionRequest,)
  }
);}
  



export const getCreateConnectionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConnection>>, TError,{data: CreateConnectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createConnection>>, TError,{data: CreateConnectionRequest}, TContext> => {

const mutationKey = ['createConnection'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConnection>>, {data: CreateConnectionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createConnection(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof createConnection>>>
    export type CreateConnectionMutationBody = CreateConnectionRequest
    export type CreateConnectionMutationError = unknown

    /**
 * @summary Create Connection
 */
export const useCreateConnection = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConnection>>, TError,{data: CreateConnectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConnection>>,
        TError,
        {data: CreateConnectionRequest},
        TContext
      > => {
      return useMutation(getCreateConnectionMutationOptions(options), queryClient);
    }
    /**
 * @summary Retrieves a connection by ID
 */
export const getFindConnectionUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}`
}

export const findConnection = async (connectionID: string, options?: RequestInit): Promise<Connection> => {
  
  return customInstance<Connection>(getFindConnectionUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getFindConnectionQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}`
    ] as const;
    }

    
export const getFindConnectionQueryOptions = <TData = Awaited<ReturnType<typeof findConnection>>, TError = void>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindConnectionQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findConnection>>> = ({ signal }) => findConnection(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindConnectionQueryResult = NonNullable<Awaited<ReturnType<typeof findConnection>>>
export type FindConnectionQueryError = void


export function useFindConnection<TData = Awaited<ReturnType<typeof findConnection>>, TError = void>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findConnection>>,
          TError,
          Awaited<ReturnType<typeof findConnection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindConnection<TData = Awaited<ReturnType<typeof findConnection>>, TError = void>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findConnection>>,
          TError,
          Awaited<ReturnType<typeof findConnection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindConnection<TData = Awaited<ReturnType<typeof findConnection>>, TError = void>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a connection by ID
 */

export function useFindConnection<TData = Awaited<ReturnType<typeof findConnection>>, TError = void>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindConnectionQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Checks the connection status
 */
export const getPingConnectionUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/ping`
}

export const pingConnection = async (connectionID: string, options?: RequestInit): Promise<void> => {
  
  return customInstance<void>(getPingConnectionUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getPingConnectionQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}/ping`
    ] as const;
    }

    
export const getPingConnectionQueryOptions = <TData = Awaited<ReturnType<typeof pingConnection>>, TError = Error>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPingConnectionQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pingConnection>>> = ({ signal }) => pingConnection(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PingConnectionQueryResult = NonNullable<Awaited<ReturnType<typeof pingConnection>>>
export type PingConnectionQueryError = Error


export function usePingConnection<TData = Awaited<ReturnType<typeof pingConnection>>, TError = Error>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pingConnection>>,
          TError,
          Awaited<ReturnType<typeof pingConnection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingConnection<TData = Awaited<ReturnType<typeof pingConnection>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pingConnection>>,
          TError,
          Awaited<ReturnType<typeof pingConnection>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingConnection<TData = Awaited<ReturnType<typeof pingConnection>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Checks the connection status
 */

export function usePingConnection<TData = Awaited<ReturnType<typeof pingConnection>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingConnection>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPingConnectionQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List databases from a connection
 */
export const getListDatabasesUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/databases`
}

export const listDatabases = async (connectionID: string, options?: RequestInit): Promise<Database[]> => {
  
  return customInstance<Database[]>(getListDatabasesUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListDatabasesQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}/databases`
    ] as const;
    }

    
export const getListDatabasesQueryOptions = <TData = Awaited<ReturnType<typeof listDatabases>>, TError = Error>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDatabasesQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDatabases>>> = ({ signal }) => listDatabases(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDatabasesQueryResult = NonNullable<Awaited<ReturnType<typeof listDatabases>>>
export type ListDatabasesQueryError = Error


export function useListDatabases<TData = Awaited<ReturnType<typeof listDatabases>>, TError = Error>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDatabases>>,
          TError,
          Awaited<ReturnType<typeof listDatabases>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDatabases<TData = Awaited<ReturnType<typeof listDatabases>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDatabases>>,
          TError,
          Awaited<ReturnType<typeof listDatabases>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDatabases<TData = Awaited<ReturnType<typeof listDatabases>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List databases from a connection
 */

export function useListDatabases<TData = Awaited<ReturnType<typeof listDatabases>>, TError = Error>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDatabases>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDatabasesQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new database
 */
export const getCreateDatabaseUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/databases`
}

export const createDatabase = async (connectionID: string,
    createDatabaseRequest: CreateDatabaseRequest, options?: RequestInit): Promise<void> => {
  
  return customInstance<void>(getCreateDatabaseUrl(connectionID),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDatabaseRequest,)
  }
);}
  



export const getCreateDatabaseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDatabase>>, TError,{connectionID: string;data: CreateDatabaseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDatabase>>, TError,{connectionID: string;data: CreateDatabaseRequest}, TContext> => {

const mutationKey = ['createDatabase'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDatabase>>, {connectionID: string;data: CreateDatabaseRequest}> = (props) => {
          const {connectionID,data} = props ?? {};

          return  createDatabase(connectionID,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDatabaseMutationResult = NonNullable<Awaited<ReturnType<typeof createDatabase>>>
    export type CreateDatabaseMutationBody = CreateDatabaseRequest
    export type CreateDatabaseMutationError = unknown

    /**
 * @summary Create a new database
 */
export const useCreateDatabase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDatabase>>, TError,{connectionID: string;data: CreateDatabaseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDatabase>>,
        TError,
        {connectionID: string;data: CreateDatabaseRequest},
        TContext
      > => {
      return useMutation(getCreateDatabaseMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Server Health & Overview
 */
export const getGetConnectionOverviewUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/overview`
}

export const getConnectionOverview = async (connectionID: string, options?: RequestInit): Promise<OverviewResponse> => {
  
  return customInstance<OverviewResponse>(getGetConnectionOverviewUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetConnectionOverviewQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}/overview`
    ] as const;
    }

    
export const getGetConnectionOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getConnectionOverview>>, TError = unknown>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectionOverviewQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectionOverview>>> = ({ signal }) => getConnectionOverview(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConnectionOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectionOverview>>>
export type GetConnectionOverviewQueryError = unknown


export function useGetConnectionOverview<TData = Awaited<ReturnType<typeof getConnectionOverview>>, TError = unknown>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectionOverview>>,
          TError,
          Awaited<ReturnType<typeof getConnectionOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConnectionOverview<TData = Awaited<ReturnType<typeof getConnectionOverview>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectionOverview>>,
          TError,
          Awaited<ReturnType<typeof getConnectionOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConnectionOverview<TData = Awaited<ReturnType<typeof getConnectionOverview>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Server Health & Overview
 */

export function useGetConnectionOverview<TData = Awaited<ReturnType<typeof getConnectionOverview>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectionOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConnectionOverviewQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List tables from a database
 */
export const getListTablesUrl = (connectionID: string,
    databaseName: string,) => {


  

  return `/connections/${connectionID}/databases/${databaseName}/tables`
}

export const listTables = async (connectionID: string,
    databaseName: string, options?: RequestInit): Promise<Table[]> => {
  
  return customInstance<Table[]>(getListTablesUrl(connectionID,databaseName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListTablesQueryKey = (connectionID: string,
    databaseName: string,) => {
    return [
    `/connections/${connectionID}/databases/${databaseName}/tables`
    ] as const;
    }

    
export const getListTablesQueryOptions = <TData = Awaited<ReturnType<typeof listTables>>, TError = Error>(connectionID: string,
    databaseName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTablesQueryKey(connectionID,databaseName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTables>>> = ({ signal }) => listTables(connectionID,databaseName, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID && databaseName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTablesQueryResult = NonNullable<Awaited<ReturnType<typeof listTables>>>
export type ListTablesQueryError = Error


export function useListTables<TData = Awaited<ReturnType<typeof listTables>>, TError = Error>(
 connectionID: string,
    databaseName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTables>>,
          TError,
          Awaited<ReturnType<typeof listTables>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTables<TData = Awaited<ReturnType<typeof listTables>>, TError = Error>(
 connectionID: string,
    databaseName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTables>>,
          TError,
          Awaited<ReturnType<typeof listTables>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTables<TData = Awaited<ReturnType<typeof listTables>>, TError = Error>(
 connectionID: string,
    databaseName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tables from a database
 */

export function useListTables<TData = Awaited<ReturnType<typeof listTables>>, TError = Error>(
 connectionID: string,
    databaseName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTables>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTablesQueryOptions(connectionID,databaseName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a table in a database
 */
export const getCreateTableUrl = (connectionID: string,
    databaseName: string,) => {


  

  return `/connections/${connectionID}/databases/${databaseName}/tables`
}

export const createTable = async (connectionID: string,
    databaseName: string,
    createTableRequest: CreateTableRequest, options?: RequestInit): Promise<void> => {
  
  return customInstance<void>(getCreateTableUrl(connectionID,databaseName),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTableRequest,)
  }
);}
  



export const getCreateTableMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{connectionID: string;databaseName: string;data: CreateTableRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{connectionID: string;databaseName: string;data: CreateTableRequest}, TContext> => {

const mutationKey = ['createTable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTable>>, {connectionID: string;databaseName: string;data: CreateTableRequest}> = (props) => {
          const {connectionID,databaseName,data} = props ?? {};

          return  createTable(connectionID,databaseName,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTableMutationResult = NonNullable<Awaited<ReturnType<typeof createTable>>>
    export type CreateTableMutationBody = CreateTableRequest
    export type CreateTableMutationError = unknown

    /**
 * @summary Create a table in a database
 */
export const useCreateTable = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{connectionID: string;databaseName: string;data: CreateTableRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTable>>,
        TError,
        {connectionID: string;databaseName: string;data: CreateTableRequest},
        TContext
      > => {
      return useMutation(getCreateTableMutationOptions(options), queryClient);
    }
    /**
 * @summary ListColumns
 */
export const getListColumnsUrl = (connectionID: string,
    databaseName: string,
    tableName: string,) => {


  

  return `/connections/${connectionID}/databases/${databaseName}/tables/${tableName}/columns`
}

export const listColumns = async (connectionID: string,
    databaseName: string,
    tableName: string, options?: RequestInit): Promise<Column[]> => {
  
  return customInstance<Column[]>(getListColumnsUrl(connectionID,databaseName,tableName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListColumnsQueryKey = (connectionID: string,
    databaseName: string,
    tableName: string,) => {
    return [
    `/connections/${connectionID}/databases/${databaseName}/tables/${tableName}/columns`
    ] as const;
    }

    
export const getListColumnsQueryOptions = <TData = Awaited<ReturnType<typeof listColumns>>, TError = unknown>(connectionID: string,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListColumnsQueryKey(connectionID,databaseName,tableName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listColumns>>> = ({ signal }) => listColumns(connectionID,databaseName,tableName, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID && databaseName && tableName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListColumnsQueryResult = NonNullable<Awaited<ReturnType<typeof listColumns>>>
export type ListColumnsQueryError = unknown


export function useListColumns<TData = Awaited<ReturnType<typeof listColumns>>, TError = unknown>(
 connectionID: string,
    databaseName: string,
    tableName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listColumns>>,
          TError,
          Awaited<ReturnType<typeof listColumns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListColumns<TData = Awaited<ReturnType<typeof listColumns>>, TError = unknown>(
 connectionID: string,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listColumns>>,
          TError,
          Awaited<ReturnType<typeof listColumns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListColumns<TData = Awaited<ReturnType<typeof listColumns>>, TError = unknown>(
 connectionID: string,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListColumns
 */

export function useListColumns<TData = Awaited<ReturnType<typeof listColumns>>, TError = unknown>(
 connectionID: string,
    databaseName: string,
    tableName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListColumnsQueryOptions(connectionID,databaseName,tableName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List database users (roles)
 */
export const getListUsersUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/users`
}

export const listUsers = async (connectionID: string, options?: RequestInit): Promise<DBUser[]> => {
  
  return customInstance<DBUser[]>(getListUsersUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListUsersQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}/users`
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = unknown


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List database users (roles)
 */

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new database user
 */
export const getCreateUserUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/users`
}

export const createUser = async (connectionID: string,
    createUserRequest: CreateUserRequest, options?: RequestInit): Promise<void> => {
  
  return customInstance<void>(getCreateUserUrl(connectionID),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserRequest,)
  }
);}
  



export const getCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{connectionID: string;data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{connectionID: string;data: CreateUserRequest}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {connectionID: string;data: CreateUserRequest}> = (props) => {
          const {connectionID,data} = props ?? {};

          return  createUser(connectionID,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = CreateUserRequest
    export type CreateUserMutationError = unknown

    /**
 * @summary Create a new database user
 */
export const useCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{connectionID: string;data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {connectionID: string;data: CreateUserRequest},
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options), queryClient);
    }
    /**
 * @summary List active sessions
 */
export const getListSessionsUrl = (connectionID: string,) => {


  

  return `/connections/${connectionID}/sessions`
}

export const listSessions = async (connectionID: string, options?: RequestInit): Promise<Session[]> => {
  
  return customInstance<Session[]>(getListSessionsUrl(connectionID),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListSessionsQueryKey = (connectionID: string,) => {
    return [
    `/connections/${connectionID}/sessions`
    ] as const;
    }

    
export const getListSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSessionsQueryKey(connectionID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) => listSessions(connectionID, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(connectionID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>
export type ListSessionsQueryError = unknown


export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 connectionID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSessions>>,
          TError,
          Awaited<ReturnType<typeof listSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSessions>>,
          TError,
          Awaited<ReturnType<typeof listSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active sessions
 */

export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 connectionID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSessionsQueryOptions(connectionID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Kill a specific session
 */
export const getKillSessionUrl = (connectionID: string,
    pid: number,) => {


  

  return `/connections/${connectionID}/sessions/${pid}`
}

export const killSession = async (connectionID: string,
    pid: number, options?: RequestInit): Promise<void> => {
  
  return customInstance<void>(getKillSessionUrl(connectionID,pid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getKillSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof killSession>>, TError,{connectionID: string;pid: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof killSession>>, TError,{connectionID: string;pid: number}, TContext> => {

const mutationKey = ['killSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof killSession>>, {connectionID: string;pid: number}> = (props) => {
          const {connectionID,pid} = props ?? {};

          return  killSession(connectionID,pid,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type KillSessionMutationResult = NonNullable<Awaited<ReturnType<typeof killSession>>>
    
    export type KillSessionMutationError = unknown

    /**
 * @summary Kill a specific session
 */
export const useKillSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof killSession>>, TError,{connectionID: string;pid: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof killSession>>,
        TError,
        {connectionID: string;pid: number},
        TContext
      > => {
      return useMutation(getKillSessionMutationOptions(options), queryClient);
    }
    