/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TesteIndexRouteImport } from './routes/teste/index'
import { Route as ConnectionsConnectionIdRouteImport } from './routes/connections/$connectionId'
import { Route as ConnectionsConnectionIdIndexRouteImport } from './routes/connections/$connectionId/index'
import { Route as ConnectionsConnectionIdUsersRouteImport } from './routes/connections/$connectionId/users'
import { Route as ConnectionsConnectionIdOverviewRouteImport } from './routes/connections/$connectionId/overview'
import { Route as ConnectionsConnectionIdMonitorRouteImport } from './routes/connections/$connectionId/monitor'
import { Route as ConnectionsConnectionIdDatabasesIndexRouteImport } from './routes/connections/$connectionId/databases/index'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameRouteImport } from './routes/connections/$connectionId/databases/$databaseName'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport } from './routes/connections/$connectionId/databases/$databaseName/index'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport } from './routes/connections/$connectionId/databases/$databaseName/tables/$tableName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIndexRoute = TesteIndexRouteImport.update({
  id: '/teste/',
  path: '/teste/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdRoute = ConnectionsConnectionIdRouteImport.update({
  id: '/connections/$connectionId',
  path: '/connections/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdIndexRoute =
  ConnectionsConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdUsersRoute =
  ConnectionsConnectionIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdOverviewRoute =
  ConnectionsConnectionIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdMonitorRoute =
  ConnectionsConnectionIdMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdDatabasesIndexRoute =
  ConnectionsConnectionIdDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameRouteImport.update({
    id: '/databases/$databaseName',
    path: '/databases/$databaseName',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionsConnectionIdDatabasesDatabaseNameRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport.update(
    {
      id: '/tables/$tableName',
      path: '/tables/$tableName',
      getParentRoute: () => ConnectionsConnectionIdDatabasesDatabaseNameRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRouteWithChildren
  '/teste/': typeof TesteIndexRoute
  '/connections/$connectionId/monitor': typeof ConnectionsConnectionIdMonitorRoute
  '/connections/$connectionId/overview': typeof ConnectionsConnectionIdOverviewRoute
  '/connections/$connectionId/users': typeof ConnectionsConnectionIdUsersRoute
  '/connections/$connectionId/': typeof ConnectionsConnectionIdIndexRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
  '/connections/$connectionId/databases/': typeof ConnectionsConnectionIdDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName/': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teste': typeof TesteIndexRoute
  '/connections/$connectionId/monitor': typeof ConnectionsConnectionIdMonitorRoute
  '/connections/$connectionId/overview': typeof ConnectionsConnectionIdOverviewRoute
  '/connections/$connectionId/users': typeof ConnectionsConnectionIdUsersRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdIndexRoute
  '/connections/$connectionId/databases': typeof ConnectionsConnectionIdDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRouteWithChildren
  '/teste/': typeof TesteIndexRoute
  '/connections/$connectionId/monitor': typeof ConnectionsConnectionIdMonitorRoute
  '/connections/$connectionId/overview': typeof ConnectionsConnectionIdOverviewRoute
  '/connections/$connectionId/users': typeof ConnectionsConnectionIdUsersRoute
  '/connections/$connectionId/': typeof ConnectionsConnectionIdIndexRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
  '/connections/$connectionId/databases/': typeof ConnectionsConnectionIdDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName/': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections/$connectionId'
    | '/teste/'
    | '/connections/$connectionId/monitor'
    | '/connections/$connectionId/overview'
    | '/connections/$connectionId/users'
    | '/connections/$connectionId/'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/databases/'
    | '/connections/$connectionId/databases/$databaseName/'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teste'
    | '/connections/$connectionId/monitor'
    | '/connections/$connectionId/overview'
    | '/connections/$connectionId/users'
    | '/connections/$connectionId'
    | '/connections/$connectionId/databases'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/connections/$connectionId'
    | '/teste/'
    | '/connections/$connectionId/monitor'
    | '/connections/$connectionId/overview'
    | '/connections/$connectionId/users'
    | '/connections/$connectionId/'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/databases/'
    | '/connections/$connectionId/databases/$databaseName/'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsConnectionIdRoute: typeof ConnectionsConnectionIdRouteWithChildren
  TesteIndexRoute: typeof TesteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/': {
      id: '/teste/'
      path: '/teste'
      fullPath: '/teste/'
      preLoaderRoute: typeof TesteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId': {
      id: '/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId/': {
      id: '/connections/$connectionId/'
      path: '/'
      fullPath: '/connections/$connectionId/'
      preLoaderRoute: typeof ConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/users': {
      id: '/connections/$connectionId/users'
      path: '/users'
      fullPath: '/connections/$connectionId/users'
      preLoaderRoute: typeof ConnectionsConnectionIdUsersRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/overview': {
      id: '/connections/$connectionId/overview'
      path: '/overview'
      fullPath: '/connections/$connectionId/overview'
      preLoaderRoute: typeof ConnectionsConnectionIdOverviewRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/monitor': {
      id: '/connections/$connectionId/monitor'
      path: '/monitor'
      fullPath: '/connections/$connectionId/monitor'
      preLoaderRoute: typeof ConnectionsConnectionIdMonitorRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/databases/': {
      id: '/connections/$connectionId/databases/'
      path: '/databases'
      fullPath: '/connections/$connectionId/databases/'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/databases/$databaseName': {
      id: '/connections/$connectionId/databases/$databaseName'
      path: '/databases/$databaseName'
      fullPath: '/connections/$connectionId/databases/$databaseName'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/databases/$databaseName/': {
      id: '/connections/$connectionId/databases/$databaseName/'
      path: '/'
      fullPath: '/connections/$connectionId/databases/$databaseName/'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRoute
    }
    '/connections/$connectionId/databases/$databaseName/tables/$tableName': {
      id: '/connections/$connectionId/databases/$databaseName/tables/$tableName'
      path: '/tables/$tableName'
      fullPath: '/connections/$connectionId/databases/$databaseName/tables/$tableName'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport
      parentRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRoute
    }
  }
}

interface ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren {
  ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}

const ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren: ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren =
  {
    ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute,
    ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute,
  }

const ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren =
  ConnectionsConnectionIdDatabasesDatabaseNameRoute._addFileChildren(
    ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren,
  )

interface ConnectionsConnectionIdRouteChildren {
  ConnectionsConnectionIdMonitorRoute: typeof ConnectionsConnectionIdMonitorRoute
  ConnectionsConnectionIdOverviewRoute: typeof ConnectionsConnectionIdOverviewRoute
  ConnectionsConnectionIdUsersRoute: typeof ConnectionsConnectionIdUsersRoute
  ConnectionsConnectionIdIndexRoute: typeof ConnectionsConnectionIdIndexRoute
  ConnectionsConnectionIdDatabasesDatabaseNameRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
  ConnectionsConnectionIdDatabasesIndexRoute: typeof ConnectionsConnectionIdDatabasesIndexRoute
}

const ConnectionsConnectionIdRouteChildren: ConnectionsConnectionIdRouteChildren =
  {
    ConnectionsConnectionIdMonitorRoute: ConnectionsConnectionIdMonitorRoute,
    ConnectionsConnectionIdOverviewRoute: ConnectionsConnectionIdOverviewRoute,
    ConnectionsConnectionIdUsersRoute: ConnectionsConnectionIdUsersRoute,
    ConnectionsConnectionIdIndexRoute: ConnectionsConnectionIdIndexRoute,
    ConnectionsConnectionIdDatabasesDatabaseNameRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren,
    ConnectionsConnectionIdDatabasesIndexRoute:
      ConnectionsConnectionIdDatabasesIndexRoute,
  }

const ConnectionsConnectionIdRouteWithChildren =
  ConnectionsConnectionIdRoute._addFileChildren(
    ConnectionsConnectionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsConnectionIdRoute: ConnectionsConnectionIdRouteWithChildren,
  TesteIndexRoute: TesteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
