/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TesteIndexRouteImport } from './routes/teste/index'
import { Route as ConnectionsConnectionIdRouteImport } from './routes/connections/$connectionId'
import { Route as ConnectionsConnectionIdLayoutRouteRouteImport } from './routes/connections/$connectionId/_layout/route'
import { Route as ConnectionsConnectionIdLayoutIndexRouteImport } from './routes/connections/$connectionId/_layout/index'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameRouteImport } from './routes/connections/$connectionId/databases/$databaseName'
import { Route as ConnectionsConnectionIdLayoutUsersRouteImport } from './routes/connections/$connectionId/_layout/users'
import { Route as ConnectionsConnectionIdLayoutOverviewRouteImport } from './routes/connections/$connectionId/_layout/overview'
import { Route as ConnectionsConnectionIdLayoutMonitorRouteImport } from './routes/connections/$connectionId/_layout/monitor'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport } from './routes/connections/$connectionId/databases/$databaseName/index'
import { Route as ConnectionsConnectionIdLayoutDatabasesIndexRouteImport } from './routes/connections/$connectionId/_layout/databases/index'
import { Route as ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport } from './routes/connections/$connectionId/databases/$databaseName/tables/$tableName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIndexRoute = TesteIndexRouteImport.update({
  id: '/teste/',
  path: '/teste/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdRoute = ConnectionsConnectionIdRouteImport.update({
  id: '/connections/$connectionId',
  path: '/connections/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdLayoutRouteRoute =
  ConnectionsConnectionIdLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdLayoutIndexRoute =
  ConnectionsConnectionIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionsConnectionIdLayoutRouteRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameRouteImport.update({
    id: '/databases/$databaseName',
    path: '/databases/$databaseName',
    getParentRoute: () => ConnectionsConnectionIdRoute,
  } as any)
const ConnectionsConnectionIdLayoutUsersRoute =
  ConnectionsConnectionIdLayoutUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ConnectionsConnectionIdLayoutRouteRoute,
  } as any)
const ConnectionsConnectionIdLayoutOverviewRoute =
  ConnectionsConnectionIdLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ConnectionsConnectionIdLayoutRouteRoute,
  } as any)
const ConnectionsConnectionIdLayoutMonitorRoute =
  ConnectionsConnectionIdLayoutMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => ConnectionsConnectionIdLayoutRouteRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionsConnectionIdDatabasesDatabaseNameRoute,
  } as any)
const ConnectionsConnectionIdLayoutDatabasesIndexRoute =
  ConnectionsConnectionIdLayoutDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => ConnectionsConnectionIdLayoutRouteRoute,
  } as any)
const ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute =
  ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport.update(
    {
      id: '/tables/$tableName',
      path: '/tables/$tableName',
      getParentRoute: () => ConnectionsConnectionIdDatabasesDatabaseNameRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdLayoutRouteRouteWithChildren
  '/teste/': typeof TesteIndexRoute
  '/connections/$connectionId/monitor': typeof ConnectionsConnectionIdLayoutMonitorRoute
  '/connections/$connectionId/overview': typeof ConnectionsConnectionIdLayoutOverviewRoute
  '/connections/$connectionId/users': typeof ConnectionsConnectionIdLayoutUsersRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
  '/connections/$connectionId/': typeof ConnectionsConnectionIdLayoutIndexRoute
  '/connections/$connectionId/databases/': typeof ConnectionsConnectionIdLayoutDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName/': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdLayoutIndexRoute
  '/teste': typeof TesteIndexRoute
  '/connections/$connectionId/monitor': typeof ConnectionsConnectionIdLayoutMonitorRoute
  '/connections/$connectionId/overview': typeof ConnectionsConnectionIdLayoutOverviewRoute
  '/connections/$connectionId/users': typeof ConnectionsConnectionIdLayoutUsersRoute
  '/connections/$connectionId/databases': typeof ConnectionsConnectionIdLayoutDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRouteWithChildren
  '/teste/': typeof TesteIndexRoute
  '/connections/$connectionId/_layout': typeof ConnectionsConnectionIdLayoutRouteRouteWithChildren
  '/connections/$connectionId/_layout/monitor': typeof ConnectionsConnectionIdLayoutMonitorRoute
  '/connections/$connectionId/_layout/overview': typeof ConnectionsConnectionIdLayoutOverviewRoute
  '/connections/$connectionId/_layout/users': typeof ConnectionsConnectionIdLayoutUsersRoute
  '/connections/$connectionId/databases/$databaseName': typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
  '/connections/$connectionId/_layout/': typeof ConnectionsConnectionIdLayoutIndexRoute
  '/connections/$connectionId/_layout/databases/': typeof ConnectionsConnectionIdLayoutDatabasesIndexRoute
  '/connections/$connectionId/databases/$databaseName/': typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  '/connections/$connectionId/databases/$databaseName/tables/$tableName': typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections/$connectionId'
    | '/teste/'
    | '/connections/$connectionId/monitor'
    | '/connections/$connectionId/overview'
    | '/connections/$connectionId/users'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/'
    | '/connections/$connectionId/databases/'
    | '/connections/$connectionId/databases/$databaseName/'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections/$connectionId'
    | '/teste'
    | '/connections/$connectionId/monitor'
    | '/connections/$connectionId/overview'
    | '/connections/$connectionId/users'
    | '/connections/$connectionId/databases'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/connections/$connectionId'
    | '/teste/'
    | '/connections/$connectionId/_layout'
    | '/connections/$connectionId/_layout/monitor'
    | '/connections/$connectionId/_layout/overview'
    | '/connections/$connectionId/_layout/users'
    | '/connections/$connectionId/databases/$databaseName'
    | '/connections/$connectionId/_layout/'
    | '/connections/$connectionId/_layout/databases/'
    | '/connections/$connectionId/databases/$databaseName/'
    | '/connections/$connectionId/databases/$databaseName/tables/$tableName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsConnectionIdRoute: typeof ConnectionsConnectionIdRouteWithChildren
  TesteIndexRoute: typeof TesteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/': {
      id: '/teste/'
      path: '/teste'
      fullPath: '/teste/'
      preLoaderRoute: typeof TesteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId': {
      id: '/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId/_layout': {
      id: '/connections/$connectionId/_layout'
      path: ''
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutRouteRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/_layout/': {
      id: '/connections/$connectionId/_layout/'
      path: '/'
      fullPath: '/connections/$connectionId/'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdLayoutRouteRoute
    }
    '/connections/$connectionId/databases/$databaseName': {
      id: '/connections/$connectionId/databases/$databaseName'
      path: '/databases/$databaseName'
      fullPath: '/connections/$connectionId/databases/$databaseName'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteImport
      parentRoute: typeof ConnectionsConnectionIdRoute
    }
    '/connections/$connectionId/_layout/users': {
      id: '/connections/$connectionId/_layout/users'
      path: '/users'
      fullPath: '/connections/$connectionId/users'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutUsersRouteImport
      parentRoute: typeof ConnectionsConnectionIdLayoutRouteRoute
    }
    '/connections/$connectionId/_layout/overview': {
      id: '/connections/$connectionId/_layout/overview'
      path: '/overview'
      fullPath: '/connections/$connectionId/overview'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutOverviewRouteImport
      parentRoute: typeof ConnectionsConnectionIdLayoutRouteRoute
    }
    '/connections/$connectionId/_layout/monitor': {
      id: '/connections/$connectionId/_layout/monitor'
      path: '/monitor'
      fullPath: '/connections/$connectionId/monitor'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutMonitorRouteImport
      parentRoute: typeof ConnectionsConnectionIdLayoutRouteRoute
    }
    '/connections/$connectionId/databases/$databaseName/': {
      id: '/connections/$connectionId/databases/$databaseName/'
      path: '/'
      fullPath: '/connections/$connectionId/databases/$databaseName/'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRoute
    }
    '/connections/$connectionId/_layout/databases/': {
      id: '/connections/$connectionId/_layout/databases/'
      path: '/databases'
      fullPath: '/connections/$connectionId/databases/'
      preLoaderRoute: typeof ConnectionsConnectionIdLayoutDatabasesIndexRouteImport
      parentRoute: typeof ConnectionsConnectionIdLayoutRouteRoute
    }
    '/connections/$connectionId/databases/$databaseName/tables/$tableName': {
      id: '/connections/$connectionId/databases/$databaseName/tables/$tableName'
      path: '/tables/$tableName'
      fullPath: '/connections/$connectionId/databases/$databaseName/tables/$tableName'
      preLoaderRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRouteImport
      parentRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRoute
    }
  }
}

interface ConnectionsConnectionIdLayoutRouteRouteChildren {
  ConnectionsConnectionIdLayoutMonitorRoute: typeof ConnectionsConnectionIdLayoutMonitorRoute
  ConnectionsConnectionIdLayoutOverviewRoute: typeof ConnectionsConnectionIdLayoutOverviewRoute
  ConnectionsConnectionIdLayoutUsersRoute: typeof ConnectionsConnectionIdLayoutUsersRoute
  ConnectionsConnectionIdLayoutIndexRoute: typeof ConnectionsConnectionIdLayoutIndexRoute
  ConnectionsConnectionIdLayoutDatabasesIndexRoute: typeof ConnectionsConnectionIdLayoutDatabasesIndexRoute
}

const ConnectionsConnectionIdLayoutRouteRouteChildren: ConnectionsConnectionIdLayoutRouteRouteChildren =
  {
    ConnectionsConnectionIdLayoutMonitorRoute:
      ConnectionsConnectionIdLayoutMonitorRoute,
    ConnectionsConnectionIdLayoutOverviewRoute:
      ConnectionsConnectionIdLayoutOverviewRoute,
    ConnectionsConnectionIdLayoutUsersRoute:
      ConnectionsConnectionIdLayoutUsersRoute,
    ConnectionsConnectionIdLayoutIndexRoute:
      ConnectionsConnectionIdLayoutIndexRoute,
    ConnectionsConnectionIdLayoutDatabasesIndexRoute:
      ConnectionsConnectionIdLayoutDatabasesIndexRoute,
  }

const ConnectionsConnectionIdLayoutRouteRouteWithChildren =
  ConnectionsConnectionIdLayoutRouteRoute._addFileChildren(
    ConnectionsConnectionIdLayoutRouteRouteChildren,
  )

interface ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren {
  ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute
  ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute
}

const ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren: ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren =
  {
    ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameIndexRoute,
    ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameTablesTableNameRoute,
  }

const ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren =
  ConnectionsConnectionIdDatabasesDatabaseNameRoute._addFileChildren(
    ConnectionsConnectionIdDatabasesDatabaseNameRouteChildren,
  )

interface ConnectionsConnectionIdRouteChildren {
  ConnectionsConnectionIdLayoutRouteRoute: typeof ConnectionsConnectionIdLayoutRouteRouteWithChildren
  ConnectionsConnectionIdDatabasesDatabaseNameRoute: typeof ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren
}

const ConnectionsConnectionIdRouteChildren: ConnectionsConnectionIdRouteChildren =
  {
    ConnectionsConnectionIdLayoutRouteRoute:
      ConnectionsConnectionIdLayoutRouteRouteWithChildren,
    ConnectionsConnectionIdDatabasesDatabaseNameRoute:
      ConnectionsConnectionIdDatabasesDatabaseNameRouteWithChildren,
  }

const ConnectionsConnectionIdRouteWithChildren =
  ConnectionsConnectionIdRoute._addFileChildren(
    ConnectionsConnectionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsConnectionIdRoute: ConnectionsConnectionIdRouteWithChildren,
  TesteIndexRoute: TesteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
