// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package contract

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ColumnDataType.
const (
	Bigint          ColumnDataType = "bigint"
	Bigserial       ColumnDataType = "bigserial"
	Boolean         ColumnDataType = "boolean"
	Bytea           ColumnDataType = "bytea"
	Char            ColumnDataType = "char"
	Date            ColumnDataType = "date"
	Decimal         ColumnDataType = "decimal"
	DoublePrecision ColumnDataType = "double_precision"
	Integer         ColumnDataType = "integer"
	Json            ColumnDataType = "json"
	Jsonb           ColumnDataType = "jsonb"
	Numeric         ColumnDataType = "numeric"
	Real            ColumnDataType = "real"
	Serial          ColumnDataType = "serial"
	Smallint        ColumnDataType = "smallint"
	Text            ColumnDataType = "text"
	Time            ColumnDataType = "time"
	Timestamp       ColumnDataType = "timestamp"
	Timestamptz     ColumnDataType = "timestamptz"
	Uuid            ColumnDataType = "uuid"
	Varchar         ColumnDataType = "varchar"
)

// Defines values for ConnectionDriver.
const (
	ConnectionDriverMysql    ConnectionDriver = "mysql"
	ConnectionDriverPostgres ConnectionDriver = "postgres"
)

// Defines values for ConnectionStatus.
const (
	ConnectionStatusError ConnectionStatus = "error"
	ConnectionStatusOk    ConnectionStatus = "ok"
)

// Defines values for CreateConnectionRequestDriver.
const (
	CreateConnectionRequestDriverMysql    CreateConnectionRequestDriver = "mysql"
	CreateConnectionRequestDriverPostgres CreateConnectionRequestDriver = "postgres"
)

// Defines values for CreateTableIndexMethod.
const (
	Brin   CreateTableIndexMethod = "brin"
	Btree  CreateTableIndexMethod = "btree"
	Gin    CreateTableIndexMethod = "gin"
	Gist   CreateTableIndexMethod = "gist"
	Hash   CreateTableIndexMethod = "hash"
	Spgist CreateTableIndexMethod = "spgist"
)

// Defines values for OverviewResponseStatus.
const (
	ONLINE      OverviewResponseStatus = "ONLINE"
	UNREACHABLE OverviewResponseStatus = "UNREACHABLE"
)

// ColumnDataType defines model for ColumnDataType.
type ColumnDataType string

// Connection defines model for Connection.
type Connection struct {
	CreatedAt *time.Time       `json:"createdAt,omitempty"`
	Driver    ConnectionDriver `json:"driver"`
	Host      string           `json:"host"`
	Id        string           `json:"id"`
	Name      string           `json:"name"`

	// Port A port value between 0 and 65535
	Port        int               `json:"port"`
	Status      *ConnectionStatus `json:"status,omitempty"`
	StatusError *string           `json:"status_error,omitempty"`
	UpdatedAt   *time.Time        `json:"updatedAt,omitempty"`
	Username    string            `json:"username"`
}

// ConnectionDriver defines model for Connection.Driver.
type ConnectionDriver string

// ConnectionStatus defines model for Connection.Status.
type ConnectionStatus string

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Driver   CreateConnectionRequestDriver `json:"driver"`
	Host     string                        `json:"host"`
	Name     string                        `json:"name"`
	Password string                        `json:"password"`
	Port     int                           `json:"port"`
	Username string                        `json:"username"`
}

// CreateConnectionRequestDriver defines model for CreateConnectionRequest.Driver.
type CreateConnectionRequestDriver string

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

// CreateTableColumn defines model for CreateTableColumn.
type CreateTableColumn struct {
	DefaultValue *string        `json:"default_value,omitempty"`
	Length       *int           `json:"length,omitempty"`
	Name         string         `json:"name"`
	Nullable     *bool          `json:"nullable,omitempty"`
	Precision    *int           `json:"precision,omitempty"`
	PrimaryKey   *bool          `json:"primary_key,omitempty"`
	Type         ColumnDataType `json:"type"`
}

// CreateTableIndex defines model for CreateTableIndex.
type CreateTableIndex struct {
	Columns []string                `json:"columns"`
	Method  *CreateTableIndexMethod `json:"method,omitempty"`
	Name    string                  `json:"name"`
	Unique  *bool                   `json:"unique,omitempty"`
}

// CreateTableIndexMethod defines model for CreateTableIndex.Method.
type CreateTableIndexMethod string

// CreateTableRequest defines model for CreateTableRequest.
type CreateTableRequest struct {
	Columns []CreateTableColumn `json:"columns"`
	Indexes *[]CreateTableIndex `json:"indexes,omitempty"`
	Name    string              `json:"name"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	CanLogin    *bool  `json:"can_login,omitempty"`
	ConnLimit   *int   `json:"conn_limit,omitempty"`
	IsSuperuser *bool  `json:"is_superuser,omitempty"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// DBUser defines model for DBUser.
type DBUser struct {
	CanLogin    bool   `json:"can_login"`
	ConnLimit   int    `json:"conn_limit"`
	IsSuperuser bool   `json:"is_superuser"`
	Name        string `json:"name"`
}

// Database defines model for Database.
type Database struct {
	Encoding      string `json:"encoding"`
	Name          string `json:"name"`
	Owner         string `json:"owner"`
	SizeFormatted string `json:"size_formatted"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// OverviewResponse defines model for OverviewResponse.
type OverviewResponse struct {
	LatencyMs int                    `json:"latency_ms"`
	Sessions  *string                `json:"sessions,omitempty"`
	Status    OverviewResponseStatus `json:"status"`
	Uptime    *string                `json:"uptime,omitempty"`
	Version   *string                `json:"version,omitempty"`
}

// OverviewResponseStatus defines model for OverviewResponse.Status.
type OverviewResponseStatus string

// Session defines model for Session.
type Session struct {
	Database string `json:"database"`
	Duration string `json:"duration"`
	IsSlow   bool   `json:"is_slow"`
	Pid      int    `json:"pid"`
	Query    string `json:"query"`
	State    string `json:"state"`
	User     string `json:"user"`
}

// Table defines model for Table.
type Table struct {
	Name     string `json:"name"`
	RowCount int64  `json:"row_count"`
	Size     int64  `json:"size"`
	Type     string `json:"type"`
}

// ConnectionId defines model for ConnectionId.
type ConnectionId = openapi_types.UUID

// DatabaseName defines model for DatabaseName.
type DatabaseName = string

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// CreateTableJSONRequestBody defines body for CreateTable for application/json ContentType.
type CreateTableJSONRequestBody = CreateTableRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Connections
	// (GET /connections)
	ListConnections(w http.ResponseWriter, r *http.Request)
	// Create Connection
	// (POST /connections)
	CreateConnection(w http.ResponseWriter, r *http.Request)
	// Retrieves a connection by ID
	// (GET /connections/{connectionID})
	FindConnection(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// List databases from a connection
	// (GET /connections/{connectionID}/databases)
	ListDatabases(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// Create a new database
	// (POST /connections/{connectionID}/databases)
	CreateDatabase(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// List tables from a database
	// (GET /connections/{connectionID}/databases/{databaseName}/tables)
	ListTables(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, databaseName DatabaseName)
	// Create a table in a database
	// (POST /connections/{connectionID}/databases/{databaseName}/tables)
	CreateTable(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, databaseName DatabaseName)
	// Get Server Health & Overview
	// (GET /connections/{connectionID}/overview)
	GetConnectionOverview(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// Checks the connection status
	// (GET /connections/{connectionID}/ping)
	PingConnection(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// List active sessions
	// (GET /connections/{connectionID}/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// Kill a specific session
	// (DELETE /connections/{connectionID}/sessions/{pid})
	KillSession(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, pid int)
	// List database users (roles)
	// (GET /connections/{connectionID}/users)
	ListUsers(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
	// Create a new database user
	// (POST /connections/{connectionID}/users)
	CreateUser(w http.ResponseWriter, r *http.Request, connectionID ConnectionId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List Connections
// (GET /connections)
func (_ Unimplemented) ListConnections(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Connection
// (POST /connections)
func (_ Unimplemented) CreateConnection(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieves a connection by ID
// (GET /connections/{connectionID})
func (_ Unimplemented) FindConnection(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List databases from a connection
// (GET /connections/{connectionID}/databases)
func (_ Unimplemented) ListDatabases(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new database
// (POST /connections/{connectionID}/databases)
func (_ Unimplemented) CreateDatabase(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tables from a database
// (GET /connections/{connectionID}/databases/{databaseName}/tables)
func (_ Unimplemented) ListTables(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, databaseName DatabaseName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a table in a database
// (POST /connections/{connectionID}/databases/{databaseName}/tables)
func (_ Unimplemented) CreateTable(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, databaseName DatabaseName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Server Health & Overview
// (GET /connections/{connectionID}/overview)
func (_ Unimplemented) GetConnectionOverview(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Checks the connection status
// (GET /connections/{connectionID}/ping)
func (_ Unimplemented) PingConnection(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active sessions
// (GET /connections/{connectionID}/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Kill a specific session
// (DELETE /connections/{connectionID}/sessions/{pid})
func (_ Unimplemented) KillSession(w http.ResponseWriter, r *http.Request, connectionID ConnectionId, pid int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List database users (roles)
// (GET /connections/{connectionID}/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new database user
// (POST /connections/{connectionID}/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request, connectionID ConnectionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListConnections operation middleware
func (siw *ServerInterfaceWrapper) ListConnections(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConnections(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConnection operation middleware
func (siw *ServerInterfaceWrapper) CreateConnection(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConnection(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindConnection operation middleware
func (siw *ServerInterfaceWrapper) FindConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindConnection(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDatabases operation middleware
func (siw *ServerInterfaceWrapper) ListDatabases(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDatabases(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatabase operation middleware
func (siw *ServerInterfaceWrapper) CreateDatabase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatabase(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTables operation middleware
func (siw *ServerInterfaceWrapper) ListTables(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	// ------------- Path parameter "databaseName" -------------
	var databaseName DatabaseName

	err = runtime.BindStyledParameterWithOptions("simple", "databaseName", chi.URLParam(r, "databaseName"), &databaseName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "databaseName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTables(w, r, connectionID, databaseName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTable operation middleware
func (siw *ServerInterfaceWrapper) CreateTable(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	// ------------- Path parameter "databaseName" -------------
	var databaseName DatabaseName

	err = runtime.BindStyledParameterWithOptions("simple", "databaseName", chi.URLParam(r, "databaseName"), &databaseName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "databaseName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTable(w, r, connectionID, databaseName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConnectionOverview operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionOverview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConnectionOverview(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PingConnection operation middleware
func (siw *ServerInterfaceWrapper) PingConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PingConnection(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KillSession operation middleware
func (siw *ServerInterfaceWrapper) KillSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	// ------------- Path parameter "pid" -------------
	var pid int

	err = runtime.BindStyledParameterWithOptions("simple", "pid", chi.URLParam(r, "pid"), &pid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KillSession(w, r, connectionID, pid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "connectionID" -------------
	var connectionID ConnectionId

	err = runtime.BindStyledParameterWithOptions("simple", "connectionID", chi.URLParam(r, "connectionID"), &connectionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connectionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r, connectionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections", wrapper.ListConnections)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/connections", wrapper.CreateConnection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}", wrapper.FindConnection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/databases", wrapper.ListDatabases)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/connections/{connectionID}/databases", wrapper.CreateDatabase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/databases/{databaseName}/tables", wrapper.ListTables)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/connections/{connectionID}/databases/{databaseName}/tables", wrapper.CreateTable)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/overview", wrapper.GetConnectionOverview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/ping", wrapper.PingConnection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/connections/{connectionID}/sessions/{pid}", wrapper.KillSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/connections/{connectionID}/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/connections/{connectionID}/users", wrapper.CreateUser)
	})

	return r
}
